# Generated by Django 3.2.12 on 2023-01-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MongoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('host', models.CharField(max_length=50, verbose_name='地址')),
                ('port', models.IntegerField(verbose_name='端口')),
                ('status', models.IntegerField(choices=[(0, '使用'), (1, '挂起')], default=1, verbose_name='状态')),
            ],
        ),
        migrations.CreateModel(
            name='SchedulerTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedulerid', models.CharField(max_length=255, verbose_name='调度id')),
                ('crontitle', models.CharField(max_length=255, verbose_name='定时任务名称')),
                ('cronspider', models.CharField(max_length=255, verbose_name='爬虫')),
                ('start_time', models.DateTimeField(auto_now=True, verbose_name='定时任务创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='SpiderTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pucode', models.CharField(max_length=50, verbose_name='pucode')),
                ('value', models.CharField(max_length=1000, verbose_name='任务详细')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=50, verbose_name='任务名称')),
                ('task_uuid', models.CharField(blank=True, max_length=50, null=True, verbose_name='任务id')),
                ('start_time', models.DateTimeField(auto_now=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('status', models.IntegerField(choices=[(0, '未启动'), (1, '正在运行'), (2, '已完成'), (3, '异常')], default=0, verbose_name='状态')),
            ],
        ),
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=50, verbose_name='任务名称')),
                ('task_uuid', models.CharField(blank=True, max_length=50, null=True, verbose_name='任务id')),
                ('start_time', models.DateTimeField(auto_now=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('status', models.IntegerField(choices=[(0, '未启动'), (1, '正在运行'), (2, '已完成'), (3, '异常'), (4, '正在停止')], default=0, verbose_name='状态')),
            ],
        ),
    ]
