# Generated by Django 3.2.16 on 2023-02-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drfapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spidertask',
            name='start_time',
            field=models.DateTimeField(auto_now=True, verbose_name='创建时间'),
        ),
    ]
