# Generated by Django 3.2.16 on 2023-02-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drfapp', '0002_spidertask_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='spidertask',
            name='project',
            field=models.CharField(default=1, max_length=100, verbose_name='项目'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spidertask',
            name='uuid',
            field=models.CharField(default=1, max_length=36, verbose_name='爬虫uuid'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='spidertask',
            name='pucode',
            field=models.CharField(max_length=100, verbose_name='爬虫'),
        ),
    ]
