# Generated by Django 3.2.16 on 2023-02-10 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drfapp', '0004_uploadfileform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UploadFileForm',
            new_name='UploadFileModel',
        ),
    ]
