# Generated by Django 3.2.16 on 2023-02-10 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drfapp', '0006_auto_20230211_0036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spidertask',
            old_name='pucode',
            new_name='spider',
        ),
    ]
