# Generated by Django 3.2.16 on 2023-02-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drfapp', '0007_rename_pucode_spidertask_spider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spidertask',
            name='project',
            field=models.CharField(choices=[(0, 'webspider'), (1, 'scrapy'), (2, 'other spideer')], default=0, max_length=2),
        ),
    ]
