# Generated by Django 4.1.7 on 2023-02-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("drfapp", "0009_test"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="_md5",
            field=models.CharField(default=1, max_length=36, verbose_name="测试md5"),
            preserve_default=False,
        ),
    ]
